export { ArrowsDownUpSVG } from './arrows/ArrowsDownUp'
export { DownArrow } from './arrows/DownArrow'
export { LeftArrow } from './arrows/LeftArrow'
export { RightArrow } from './arrows/RightArrow'
export { ThinLeftArrow } from './arrows/ThinLeftArrow'
export { ThinRightArrow } from './arrows/ThinRightArrow'

export { GitHubSVG } from './social/GitHub'
export { TelegramSVG } from './social/Telegram'

export { AddUserSVG } from './AddUser'
export { CartSVG } from './Cart'
export { CheckSVG } from './Check'
export { CloseSVG } from './Close'
export { CrossedOutEyeSVG } from './CrossedOutEye'
export { EmailSVG } from './Email'
export { EyeSVG } from './Eye'
export { HomeSVG } from './Home'
export { ListSVG } from './List'
export { LockSVG } from './Lock'
export { LoginSVG } from './Login'
export { SearchSVG } from './Search'
export { SettingsSVG } from './Settings'
export { TrashSVG } from './Trash'
